[project]
name = "discord-ext-streaming"
version = "0.1.0"
description = "An discord.py extension for voice recording"
readme = "README.md"
authors = [
    { name = "sizumita", email = "github@smdr.io" }
]
requires-python = ">=3.13"
dependencies = ["discord.py", "audioop-lts; python_version >= '3.13'"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/discord"]
